MIRUCTL(1) "miructl Manual" "Miru"

# NAME 

miructl - Control utility for _miru-daemon_(1)

# USAGE 

_miructl_ provides 2 commands:
- _toggle_ : Toggles the zoom overlay
- _quit_ : Quits _miru-daemon_


# Setting up a keybind

_miructl_ can be used in  a compositor-level keybind (Niri, Hyprland, MangoWM etc) and pressing that keybind should run _miructl toggle_.

See:
https://codeberg.org/Vaishnav-Sabari-Girish/miru#setting-up-a-keybind

# See Also

_miru-daemon_(1)


# AUTHORS 

Maintained by Vaishnav-Sabari-Girish <vaishnav.sabari.girish@gmail.com>. Up-to-date sources can be found at:
- https://codeberg.org/Vaishnav-Sabari-Girish/miru
- https://github.com/Vaishnav-Sabari-Girish/miru. 
Please submit any issues and PR's to 
https://codeberg.org/Vaishnav-Sabari-Girish/miru.
